In [1]:
import pandas as pd
import pickle

Jensen Shannon Divergence per FP in EU and USA dataset (rows: EU topics, columns: USA topics)

In [2]:
JSD_FP4 = pd.read_pickle('compared_FPs/JSD_FP4')
JSD_FP4

,0,1,2,3,4,5,6,7,8,9
0,0.270757,0.447847,0.451114,0.45337,0.356007,0.465329,0.477307,0.35341,0.414458,0.442594
1,0.477012,0.403838,0.537725,0.367193,0.45301,0.495539,0.396412,0.44066,0.458194,0.409857
2,0.457714,0.45754,0.518027,0.429708,0.428687,0.484062,0.361793,0.439037,0.437639,0.433404
3,0.374121,0.476859,0.380474,0.491515,0.343838,0.484284,0.497303,0.464642,0.45698,0.502111
4,0.383115,0.458783,0.464216,0.473886,0.412654,0.481799,0.456624,0.43878,0.448309,0.463823
5,0.337044,0.44558,0.469327,0.396998,0.405862,0.459785,0.49681,0.296878,0.449951,0.352029
6,0.493461,0.497834,0.544264,0.495273,0.448973,0.507973,0.452962,0.480594,0.478239,0.502347
7,0.420317,0.349362,0.460087,0.446958,0.341643,0.465742,0.475499,0.423907,0.43433,0.447924
8,0.378118,0.461469,0.504338,0.436763,0.431853,0.513413,0.504467,0.3774,0.474775,0.435238
9,0.328447,0.467051,0.476822,0.4837,0.417262,0.477756,0.488137,0.404716,0.441236,0.455897

In [3]:
JSD_FP5 = pd.read_pickle('compared_FPs/JSD_FP5')
JSD_FP5

,0,1,2,3,4,5,6,7,8,9
0,0.444925,0.477077,0.453774,0.4778,0.27598,0.341546,0.345851,0.500699,0.445482,0.453262
1,0.435886,0.417275,0.316719,0.472115,0.360154,0.43797,0.22121,0.468735,0.456262,0.458997
2,0.372255,0.459717,0.437678,0.402236,0.296048,0.252922,0.38313,0.467186,0.391818,0.395041
3,0.410217,0.337214,0.3462,0.38482,0.282111,0.40975,0.263095,0.424052,0.409009,0.415458
4,0.461291,0.43956,0.435512,0.328386,0.377872,0.475145,0.418274,0.388811,0.475142,0.486149
5,0.362375,0.366444,0.442586,0.369582,0.370741,0.346193,0.423911,0.44215,0.429012,0.351638
6,0.454803,0.441799,0.422258,0.333244,0.345073,0.48056,0.411902,0.356554,0.468207,0.485778
7,0.349438,0.44024,0.296985,0.453251,0.322093,0.37641,0.308797,0.440714,0.401555,0.400821
8,0.312145,0.450629,0.356577,0.425784,0.417005,0.418619,0.408823,0.401157,0.437591,0.41181
9,0.367876,0.422455,0.330623,0.428502,0.331094,0.385985,0.323425,0.443709,0.275994,0.385442

In [4]:
JSD_FP6 = pd.read_pickle('compared_FPs/JSD_FP6')
JSD_FP6

,0,1,2,3,4,5,6,7,8,9
0,0.383122,0.272826,0.454866,0.345687,0.453023,0.480496,0.369974,0.429404,0.405198,0.433174
1,0.381328,0.48943,0.394739,0.456004,0.253964,0.393673,0.398178,0.395673,0.422196,0.377831
2,0.233135,0.427526,0.418726,0.490217,0.49331,0.446399,0.464911,0.459254,0.349361,0.386882
3,0.433161,0.504597,0.424819,0.506598,0.294806,0.460901,0.449469,0.460068,0.439316,0.476948
4,0.352978,0.434031,0.382515,0.424796,0.386586,0.383247,0.395173,0.363302,0.413792,0.340468
5,0.326729,0.366761,0.407715,0.424871,0.431663,0.40845,0.337249,0.398369,0.387154,0.421094
6,0.316066,0.411582,0.425852,0.438067,0.44776,0.441439,0.300491,0.406079,0.41887,0.392789
7,0.266784,0.349438,0.42921,0.411441,0.436632,0.4352,0.308918,0.37111,0.411871,0.400946
8,0.325456,0.445228,0.219167,0.452329,0.393361,0.268562,0.433454,0.372954,0.219031,0.286409
9,0.219804,0.373905,0.373135,0.394709,0.372055,0.396971,0.374818,0.355603,0.368607,0.312365

In [5]:
JSD_FP7 = pd.read_pickle('compared_FPs/JSD_FP7')
JSD_FP7

,0,1,2,3,4,5,6,7,8,9
0,0.482215,0.413233,0.374762,0.479336,0.438168,0.485251,0.340847,0.51717,0.437958,0.445067
1,0.434337,0.279003,0.314433,0.410201,0.181895,0.313712,0.330471,0.372273,0.396785,0.370684
2,0.382648,0.289557,0.355791,0.420255,0.425976,0.437037,0.272922,0.473914,0.434984,0.393591
3,0.416846,0.406868,0.431592,0.31984,0.424198,0.3759,0.417062,0.458631,0.398613,0.263288
4,0.480314,0.41771,0.364547,0.335721,0.394934,0.391432,0.445415,0.466978,0.188669,0.37914
5,0.396387,0.222309,0.409356,0.453675,0.417831,0.449862,0.224212,0.443753,0.436796,0.352186
6,0.233641,0.367334,0.409454,0.374121,0.430792,0.388555,0.378401,0.451631,0.397381,0.313769
7,0.43908,0.337514,0.412889,0.423324,0.373316,0.430271,0.389054,0.270459,0.370264,0.24639
8,0.472197,0.356137,0.172009,0.460148,0.295541,0.454376,0.372263,0.449071,0.446679,0.449651
9,0.511226,0.459029,0.376256,0.475154,0.441338,0.489509,0.454246,0.499735,0.290779,0.428214

In [6]:
JSD_H2020 = pd.read_pickle('compared_FPs/JSD_H2020')
JSD_H2020

,0,1,2,3,4,5,6,7,8,9
0,0.233118,0.401945,0.34608,0.428842,0.403028,0.398809,0.378835,0.287505,0.40479,0.470668
1,0.269706,0.289891,0.276671,0.330751,0.339795,0.318086,0.330387,0.350833,0.369724,0.363457
2,0.34099,0.334309,0.223026,0.300564,0.201478,0.349816,0.367179,0.321751,0.324053,0.323906
3,0.36895,0.401184,0.342614,0.344942,0.302149,0.336686,0.309405,0.307502,0.433485,0.370376
4,0.377199,0.380329,0.315765,0.347901,0.243355,0.306439,0.244972,0.223125,0.396923,0.377935
5,0.368166,0.392218,0.359812,0.381484,0.316185,0.309293,0.232128,0.334159,0.432673,0.415863
6,0.381084,0.365428,0.335677,0.395348,0.27051,0.262223,0.301004,0.211384,0.281146,0.411691
7,0.418883,0.416461,0.37018,0.386875,0.222083,0.341926,0.318904,0.352637,0.458515,0.411704
8,0.326295,0.4017,0.342632,0.406462,0.35117,0.379439,0.366674,0.269458,0.426714,0.450191
9,0.366008,0.34971,0.196931,0.284672,0.299312,0.393682,0.396136,0.379169,0.378998,0.304101